Peer testing update
jpabadir/pace-c pull request #317
Opened 2020-11-25 17:51 UTC by wrc9817

2020-11-27 10:16 UTC, aleksssk approved these changes
Nice work

2020-11-29 03:04 UTC, KatrinaMart requested changes
Thanks for filling out the chart.
We also have to include any issues that were discovered during the sessions, prioritized as either high, medium, or low. Did your participants mention anything that we could improve on?
The instructor also wants us to add "any quoted comments you obtained from the participants" to explain the graph that we'll obtain from the Heuristics Evaluation Google Forms. Did the participants make any notable comments that we could include?
Once my comments have been addressed, I can approve the PR. Thanks!

2020-11-30 17:34 UTC, jpabadir approved these changes

2020-11-30 18:09 UTC, KatrinaMart commented on documentation/peer-testing-1/peer-testing-report.md
> +- In the list of mentor's task, there is one that asks participants to find help page. A help page or FAQ should be built.
I think this may have just been a discrepancy between the wording in the list of tasks that were displayed and the 'Mentor Tutorial'.

2020-11-30 18:15 UTC, KatrinaMart approved these changes

2020-12-01 08:16 UTC, merged