(Please don't review yet) 349 mentortutorial test
jpabadir/pace-c pull request #358
Opened 2021-01-17 17:27 UTC by aleksssk

349 mentortutorial test

2021-01-18 16:38 UTC, jpabadir requested changes
I deleted the comment you put above your test, because I thought it was extraneous: the test name accurately describes what is going on in the test. Feel free to add it back if you disagree with me. 

I would have liked to see a couple more tests in this PR checking whether or not some of the elements have the right type: check that you have <p> elements with the right text, <h3>s with the right text, etc. Also, it'd be great if you can check that the little <svg>s we have are rendering right. Inspect the page and have a look to see what you should be expecting. 

I'd add those before you merge. 

I also pushed some fixes to your PR. You can have a look at them under 'commits' and ask if you have any questions.

2021-01-19 17:23 UTC, aleksssk commented
Thanks for the feedback! I will add unit tests to make sure the headers and paragraphs are working

2021-01-20 05:29 UTC, KatrinaMart approved these changes
Thanks for adding some additional tests :)

2021-01-20 16:55 UTC, jpabadir approved these changes

2021-01-20 16:57 UTC, merged