505 aleks presentation
jpabadir/pace-c pull request #514
Opened 2021-03-30 18:13 UTC by aleksssk

Added presentation part and intro video

2021-04-05 16:52 UTC, jpabadir requested changes
Very good work, Aleks. Only issue: I have no sound on your intro video. Can you reupload that video with a little voiceover recording of you introducing yourself?

2021-04-05 18:12 UTC, jpabadir approved these changes

2021-04-05 21:57 UTC, KatrinaMart approved these changes
Nice work! I like the images that you added for the 'Target Audience' slide :)

2021-04-06 13:52 UTC, wrc9817 approved these changes
Nice work!

2021-04-07 14:57 UTC, merged